### ISSUE TITLE
react16.4.2，无法引入 MobilePDFReader

### ISSUE THREAD

**Issue by qhy90223** [forthealllight/react-read-pdf#1]
环境为umi2.0,react16.4.2，安装完成后，无法引入 MobilePDFReader，查看node_modeles，没有看到lib文件夹，请问下如何正确引入还是我需要执行真么操作，
-------------
更新：已经解决，需要自己安装后 run lib

**Comment by forthealllight** [comment]
不好意思，刚才版本打错了，现在更新到最新版就可以了，我升级了npm包，最新版本是2.0.7，npm i -s react-read-pdf@2.0.7即可

**Comment by forthealllight** [comment]
> 环境为umi2.0,react16.4.2，安装完成后，无法引入 MobilePDFReader，查看node_modeles，没有看到lib文件夹，请问下如何正确引入还是我需要执行真么操作

不好意思，刚才版本打错了，现在更新到最新版就可以了，我升级了npm包，最新版本是2.0.7，npm i -s react-read-pdf@2.0.7即可

**Comment by baihuaiyu00** [comment]
移动端测试 样式还是存在问题，主要在于footer与header大小，我这边使用时backgroud-size过大

**Comment by forthealllight** [comment]
> 移动端测试 样式还是存在问题，主要在于footer与header大小，我这边使用时backgroud-size过大

可以用自己的footer和header哦，可以设置isShowHeader和isShowFooter为false，这样就可以用自己的

**Comment by 1048034876** [comment]
我安装完2.0.7版本后，一旦引入react-read-pdf，页面控制台会报错，提示only one instance of babel-polyfill is allowed，不引入就没问题
![image](https://user-images.githubusercontent.com/24405290/52698606-c7897480-2fae-11e9-80e8-10988038f8f3.png)
![image](https://user-images.githubusercontent.com/24405290/52698636-dbcd7180-2fae-11e9-9437-aa7567064023.png)

**Comment by forthealllight** [comment]
> 我安装完2.0.7版本后，一旦引入react-read-pdf，页面控制台会报错，提示only one instance of babel-polyfill is allowed，不引入就没问题
> ![image](https://user-images.githubusercontent.com/24405290/52698606-c7897480-2fae-11e9-80e8-10988038f8f3.png)
> ![image](https://user-images.githubusercontent.com/24405290/52698636-dbcd7180-2fae-11e9-9437-aa7567064023.png)

这个应该是引入了2次babel-polyfill。你在你的项目中是不是也引入了babel-polyfill。

**Comment by forthealllight** [comment]
你看下你的项目是不是引入了两次babel-polyfill～

**Comment by FriendsA** [comment]
> 你看下你的项目是不是引入了两次babel-polyfill～

请问项目本来就引入了babel-polyfill,该如何正确引用这个呢?

**Comment by FriendsA** [comment]
在项目入口把entry : ['babel-polyfill', './src/index']改成 entry : ['./src/index']可以解决重复引用的问题.
