### ISSUE TITLE
按流程引入 浏览器打开时会报Uncaught Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded

### ISSUE THREAD

**Issue by FriendsA** [forthealllight/react-read-pdf#3]
Uncaught Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded

使用页面会报这个错误,我看到CSDN上也有个人有同样的问题.
同样问题地址: https://blog.csdn.net/liwusen/article/details/83381284

**Comment by FriendsA** [comment]
好像是因为我的react版本是15+导致的,看npm的介绍应该是需要react16+.
请问哪个版本支持react15+呢?

**Comment by forthealllight** [comment]
> 好像是因为我的react版本是15+导致的,看npm的介绍应该是需要react16+.
> 请问哪个版本支持react15+呢?

sorry，暂时不支持16.0以下版本的react。

**Comment by forthealllight** [comment]
> 好像是因为我的react版本是15+导致的,看npm的介绍应该是需要react16+.
> 请问哪个版本支持react15+呢?

嗯哼，你可以尝试自己修改以下，在component里面的两个组建。

将16.x的组建的生命周期降级到15.x，并且ref的用法也降级。不好意思，当时开发这个npm包的时候

只考虑了react16+的版本，并不兼容15.x及以下，sorry。

**Comment by sixiaodong123** [comment]
Error: only one instance of babel-polyfill is allowed

引用该react-read-pdf的时候出现该错误
